services:
  mysql:
    image: mysql:8.2
    container_name: final_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - final-mysql-data:/var/lib/mysql
volumes:
  final-mysql-data:
